apiVersion: v1
kind: Pod
metadata:
  labels:
    run: test-mail
  name: test-mail
spec:
  containers:
    - image: kristoyoyo/mailjet-sender:v0.2
      imagePullPolicy: Always
      name: test-mail
      resources:
        limits:
          cpu: 50m
          memory: 50Mi
        requests:
          cpu: 50m
          memory: 50Mi
      env:
        - name: API_KEY
          value: "${API_KEY}"
        - name: API_SECRET
          value: "${API_SECRET}"
        - name: FROM
          value: "${FROM}"
        - name: TO
          value: "${TO}"
  restartPolicy: Never
